"""Request context management for trace IDs and request-scoped data.

This module provides context variables for tracking requests through the
application stack, enabling correlation of logs and error tracking.
"""

import contextvars
import uuid
from typing import Optional

# Context variables for request-scoped data
_trace_id_context: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "trace_id",
    default=None,
)
_request_id_context: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "request_id",
    default=None,
)


def generate_trace_id() -> str:
    """Generate a new trace ID.

    Trace IDs are UUIDs that uniquely identify a request for debugging
    and request tracking purposes.

    Returns:
        New UUID4 as string (36 characters)

    Example:
        >>> trace_id = generate_trace_id()
        >>> trace_id
        '550e8400-e29b-41d4-a716-446655440000'
    """
    return str(uuid.uuid4())


def set_trace_id(trace_id: str) -> None:
    """Set the trace ID for the current request context.

    This is typically called by middleware when a request is received.

    Args:
        trace_id: Trace ID to set (should be generated by generate_trace_id())

    Example:
        >>> set_trace_id("550e8400-e29b-41d4-a716-446655440000")
        >>> get_trace_id()
        '550e8400-e29b-41d4-a716-446655440000'
    """
    _trace_id_context.set(trace_id)


def get_trace_id() -> str:
    """Get the trace ID for the current request context.

    If no trace ID is set, generates a new one.

    Returns:
        Current trace ID or newly generated one

    Example:
        >>> trace_id = get_trace_id()
        >>> len(trace_id)
        36
    """
    trace_id = _trace_id_context.get()
    if trace_id is None:
        trace_id = generate_trace_id()
        set_trace_id(trace_id)
    return trace_id


def set_request_id(request_id: str) -> None:
    """Set the request ID for the current request context.

    Request IDs can be different from trace IDs and may come from
    external sources (e.g., X-Request-ID header).

    Args:
        request_id: Request ID to set

    Example:
        >>> set_request_id("external-request-123")
    """
    _request_id_context.set(request_id)


def get_request_id() -> Optional[str]:
    """Get the request ID for the current request context.

    Returns:
        Current request ID or None if not set

    Example:
        >>> request_id = get_request_id()
    """
    return _request_id_context.get()


def clear_context() -> None:
    """Clear all context variables.

    This is typically called at the end of request processing to prevent
    context leakage in async scenarios.

    Example:
        >>> clear_context()
    """
    _trace_id_context.set(None)
    _request_id_context.set(None)
