from types import SimpleNamespace
from unittest.mock import MagicMock

from haystack import Document

from certus_ask.pipelines import preprocessing


def test_presidio_anonymizer_strict_mode_quarantines(monkeypatch):
    """Documents containing PII should be quarantined when strict mode is on."""
    analyzer = MagicMock()
    analyzer.analyze.side_effect = [
        [SimpleNamespace(entity_type="EMAIL", score=0.95, start=0, end=5)],
        [],
    ]
    anonymizer = MagicMock()

    monkeypatch.setattr("certus_ask.pipelines.preprocessing.get_analyzer", lambda: analyzer)
    monkeypatch.setattr("certus_ask.pipelines.preprocessing.get_anonymizer", lambda: anonymizer)

    pii_doc = Document(content="Reach me at test@example.com", meta={"id": "pii"})
    clean_doc = Document(content="Nothing sensitive here", meta={"id": "clean"})

    component = preprocessing.PresidioAnonymizer(strict_mode=True)
    result = component.run([pii_doc, clean_doc])

    assert [doc.meta["id"] for doc in result["documents"]] == ["clean"]
    assert [doc.meta["id"] for doc in result["quarantined"]] == ["pii"]
    anonymizer.anonymize.assert_not_called()


def test_presidio_anonymizer_lenient_masks_and_marks_metadata(monkeypatch):
    """PII should be anonymized and metadata annotated when strict mode is off."""
    analyzer = MagicMock()
    analyzer.analyze.return_value = [SimpleNamespace(entity_type="PHONE_NUMBER", score=0.8, start=0, end=5)]

    class DummyAnonymizer:
        def anonymize(self, text, analyzer_results):
            return SimpleNamespace(text="<PHONE>")

    monkeypatch.setattr("certus_ask.pipelines.preprocessing.get_analyzer", lambda: analyzer)
    monkeypatch.setattr("certus_ask.pipelines.preprocessing.get_anonymizer", lambda: DummyAnonymizer())

    doc = Document(content="555-0100", meta={"id": "pii"})
    component = preprocessing.PresidioAnonymizer(strict_mode=False)
    result = component.run([doc])

    anonymized = result["documents"][0]
    assert anonymized.content == "<PHONE>"
    assert anonymized.meta["pii_anonymized"] is True
    assert anonymized.meta["pii_count"] == 1
    assert result["quarantined"] == []


def test_logging_document_writer_builds_metadata_preview(monkeypatch):
    """Writer should return metadata preview generated by enrichment helper."""

    class DummyWriter:
        def __init__(self, document_store, policy):
            self.document_store = document_store
            self.policy = policy

        def run(self, documents):
            return {"documents_written": len(documents)}

    monkeypatch.setattr("certus_ask.pipelines.preprocessing.DocumentWriter", DummyWriter)

    def fake_enrich(docs, **ctx):
        return [{"doc_id": doc.meta["id"], "workspace_id": ctx.get("workspace_id")} for doc in docs]

    monkeypatch.setattr(
        preprocessing,
        "enrich_documents_with_metadata",
        fake_enrich,
    )

    docs = [Document(content="chunk", meta={"id": "chunk-1"})]

    writer = preprocessing.LoggingDocumentWriter(document_store=MagicMock())
    result = writer.run(docs, metadata_context={"workspace_id": "ws-123"})

    assert result["documents_written"] == 1
    assert result["metadata_preview"] == [{"doc_id": "chunk-1", "workspace_id": "ws-123"}]
