from __future__ import annotations

import json
import shutil
from pathlib import Path
from types import SimpleNamespace


class SampleSecurityScanner:
    """Lightweight scanner stub that copies canonical artifacts for smoke tests."""

    def __init__(self, sample_source: Path):
        self.sample_source = sample_source
        if not self.sample_source.exists():
            raise FileNotFoundError(
                f"Sample scan artifacts not found at {self.sample_source}. "
                "Set CERTUS_ASSURANCE_CASE_STUDY_SOURCE to override."
            )

    async def run(
        self,
        profile: str,
        workspace: Path,
        manifest_text: str,
        export_dir: Path,
        bundle_id: str,
    ) -> SimpleNamespace:
        dest = Path(export_dir) / bundle_id
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(self.sample_source, dest)
        self._ensure_required_files(dest)
        return SimpleNamespace(artifacts=dest)

    def _ensure_required_files(self, bundle: Path) -> None:
        """Create placeholder artifacts that the tutorials expect."""
        zap_report = bundle / "zap-report.json"
        zap_source = bundle / "zap-dast.sarif.json"
        if not zap_report.exists():
            if zap_source.exists():
                zap_report.write_text(zap_source.read_text(encoding="utf-8"), encoding="utf-8")
            else:
                zap_report.write_text(json.dumps({"findings": []}, indent=2), encoding="utf-8")

        summary = bundle / "summary.json"
        if not summary.exists():
            summary.write_text(
                json.dumps(
                    {
                        "status": "SUCCEEDED",
                        "notes": "Generated by SampleSecurityScanner for smoke tests",
                    },
                    indent=2,
                ),
                encoding="utf-8",
            )
